### ISSUE TITLE
Unhandled exception: Incoming.on_transfer: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ted-ross** [amqp/rhea#347]
This error occurs frequently in my Node.js program that uses rhea.  It unfortunately causes my whole program to exit.  As it occurs on incoming messages, there appears to be no place to wrap the operation in a try-catch.

I suspect that the incoming message is fragmented into multiple transfers and that the last transfer may contain no content.

The stack trace is here.  I am using version 1.0.24.

```events.js:291
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'length' of undefined
    at Incoming.on_transfer (/home/me/myproject/node_modules/rhea/lib/session.js:315:101)
    at Session.on_transfer (/home/me/myproject/node_modules/rhea/lib/session.js:755:19)
    at Connection.<computed> [as on_transfer] (/home/me/myproject/node_modules/rhea/lib/connection.js:809:30)
    at c.dispatch (/home/me/myproject/node_modules/rhea/lib/types.js:910:33)
    at Transport.read (/home/me/myproject/node_modules/rhea/lib/transport.js:109:36)
    at SaslClient.read (/home/me/myproject/node_modules/rhea/lib/sasl.js:328:26)
    at Connection.input (/home/me/myproject/node_modules/rhea/lib/connection.js:543:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
Emitted 'error' event on Container instance at:
    at Container.dispatch (/home/me/myproject/node_modules/rhea/lib/container.js:41:33)
    at Connection.dispatch (/home/me/myproject/node_modules/rhea/lib/connection.js:261:40)
    at Connection.input (/home/me/myproject/node_modules/rhea/lib/connection.js:561:18)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by grs** [comment]
You should be able to handle the 'error' event on the connection or the container, which would at least prevent the program exiting.

I have a tentative fix at https://github.com/amqp/rhea/pull/349. Are you able to verify whether that fixes your issue?

**Comment by ted-ross** [comment]
#349 appears to fix the problem.  I will also add an 'error' handler to prevent exiting.

Thanks!

**Comment by ted-ross** [comment]
Fixed in version 2.0.0

**Comment by eliorahy** [comment]
@grs @ted-ross This is still happening for us, we're using version 3.0.0

`[connection-1] disconnected TypeError: Cannot read properties of undefined (reading 'length')
    at Function.concat (node:buffer:585:19)
    at Incoming.on_transfer (C:\opt\dev\app\node_modules\rhea\lib\session.js:364:83)
    at Session.on_transfer (C:\opt\dev\app\node_modules\rhea\lib\session.js:764:19)
    at Connection.<computed> [as on_transfer] (C:\opt\dev\appnode_modules\rhea\lib\connection.js:855:30)
    at c.dispatch (C:\opt\dev\appnode_modules\rhea\lib\types.js:946:33)
    at Transport.read (C:\opt\dev\app\node_modules\rhea\lib\transport.js:117:36)
    at SaslClient.read (C:\opt\dev\app\node_modules\rhea\lib\sasl.js:344:26)
    at Connection.input (C:\opt\dev\app\node_modules\rhea\lib\connection.js:567:37)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`
